# Use root/koodikummit as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: koodikummit

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

